service: api-back-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    JWKS_URI: 'https://YOUR-TENANT.us.auth0.com/.well-known/jwks.json'
    AUDIENCE: 'PRUEBA-OF-YOUR-API' 
    TOKEN_ISSUER: 'pk_test_LsRBKejzCOEEWosw'

functions:
  getDatosCliente:
    handler: handler.getDatosCliente
    events:
      - httpApi:
          path: /datoscliente
          method: get
          authorizer: auth
  auth:
    handler: handler.authorize
    description: custom authorizer para auth0